import {
  mkdir,
  readdir,
  readFile,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { copyFile } from "node:fs/promises";
import { resolve } from "node:path";
import { generatePageHtml } from "./html-generator.js";

async function readJson(filePath) {
  const content = await readFile(filePath, "utf8");
  return JSON.parse(content);
}

function toBaseName(fileName) {
  return fileName.replace(/\.json$/i, "");
}

const GENERATED_FILE_HEADER =
  "Auto-generated by npm run publish. Do not edit dist-publish files directly. Update source files in src/ or server/publish/ and republish.";

function withGeneratedHtmlHeader(content) {
  if (process.env.NODE_ENV !== "CI") {
    const html = String(content || "");
    const comment = `<!-- ${GENERATED_FILE_HEADER} -->`;
    const doctypeMatch = html.match(/^\s*<!doctype[^>]*>/i);

    if (!doctypeMatch) {
      return `${comment}\n${html}`;
    }

    const doctype = doctypeMatch[0];
    const rest = html.slice(doctype.length);
    return `${doctype}\n${comment}${rest}`;
  }
  return "";
}

function stripViteClientScript(html) {
  return String(html || "").replace(
    /<script\s+type=["']module["']\s+src=["']\/?@vite\/client["']><\/script>\s*/g,
    "",
  );
}

function useAbsolutePublishAssetPaths(html) {
  return String(html || "")
    .replace(/href="\.\/theme\.css"/g, 'href="/theme.css"')
    .replace(/href="\.\/base\.css"/g, 'href="/base.css"')
    .replace(/src="\.\/published\.js"/g, 'src="/published.js"');
}

function normalizePublishedUrlPath(rawValue, fallbackValue = "") {
  const raw = String(rawValue || fallbackValue || "").trim();
  if (!raw) {
    return "";
  }

  const withoutQuery = raw.split("?")[0].split("#")[0];
  const normalized = withoutQuery.replace(/^\/+/, "").replace(/\/+$/, "");
  return normalized;
}

function appendTokenValuesFromObject(target, value, prefix = "") {
  if (!value || typeof value !== "object") {
    return;
  }

  for (const [key, nested] of Object.entries(value)) {
    const normalizedKey = String(key || "").trim();
    if (!normalizedKey) {
      continue;
    }

    const path = prefix ? `${prefix}.${normalizedKey}` : normalizedKey;
    if (Array.isArray(nested)) {
      const joined = nested.map((item) => String(item || "")).join(", ");
      target[path] = joined;
      target[path.toUpperCase()] = joined;
      continue;
    }

    if (nested && typeof nested === "object") {
      appendTokenValuesFromObject(target, nested, path);
      continue;
    }

    if (
      typeof nested === "string" ||
      typeof nested === "number" ||
      typeof nested === "boolean"
    ) {
      target[path] = String(nested);
      target[path.toUpperCase()] = String(nested);
    }
  }
}

function buildItemTemplateTokenValues(itemConfig = {}) {
  const tokenValues = {};

  const rawUrl =
    itemConfig?.url ||
    itemConfig?.metadata?.url ||
    itemConfig?.metadata?.sourceUrl;
  const computedUrl = rawUrl
    ? String(rawUrl)
        .split("?")[0]
        .split("#")[0]
        .replace(/^\/+/, "")
        .replace(/\/+$/, "")
    : undefined;

  appendTokenValuesFromObject(tokenValues, {
    id: itemConfig?.id,
    title: itemConfig?.title,
    excerpt: itemConfig?.excerpt,
    tags: itemConfig?.tags,
    url: computedUrl ?? itemConfig?.url,
  });

  appendTokenValuesFromObject(tokenValues, itemConfig?.metadata || {});
  return tokenValues;
}

async function copyDirectoryRecursive(sourceDir, targetDir) {
  let sourceStats;
  try {
    sourceStats = await stat(sourceDir);
  } catch {
    return;
  }

  if (!sourceStats.isDirectory()) {
    return;
  }

  await mkdir(targetDir, { recursive: true });
  const entries = await readdir(sourceDir, { withFileTypes: true });

  for (const entry of entries) {
    const sourcePath = resolve(sourceDir, entry.name);
    const targetPath = resolve(targetDir, entry.name);

    if (entry.isDirectory()) {
      await copyDirectoryRecursive(sourcePath, targetPath);
      continue;
    }

    if (entry.isFile()) {
      await copyFile(sourcePath, targetPath);
    }
  }
}

async function copyComponentStyles(appRoot, outputDir) {
  const componentsDir = resolve(appRoot, "src/website/components");
  const stylesDir = resolve(outputDir, "owb-styles");
  await mkdir(stylesDir, { recursive: true });

  let entries = [];
  try {
    entries = await readdir(componentsDir, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const name = entry.name;
    const srcPath = resolve(componentsDir, name, "styles.css");
    const destPath = resolve(stylesDir, `${name}.css`);
    try {
      await copyFile(srcPath, destPath);
    } catch {
      // Missing style files are optional in published output.
    }
  }

  // Altcha renders into the captcha component's shadow DOM; bundle its CSS
  // alongside captcha styles so the widget is styled in published output.
  try {
    const altchaCssPath = resolve(
      appRoot,
      "node_modules/altcha/dist/external/altcha.css",
    );
    const altchaCss = await readFile(altchaCssPath, "utf8");
    const captchaCssPath = resolve(stylesDir, "captcha.css");
    let existing = "";
    try {
      existing = await readFile(captchaCssPath, "utf8");
    } catch {}
    await writeFile(captchaCssPath, `${existing}\n/* altcha */\n${altchaCss}`);
  } catch {
    // Altcha CSS is optional; skip silently if not installed.
  }
}

export async function publishSite({
  contentRoot,
  outputDir,
  appRoot,
  siteUrl,
}) {
  const pagesDir = resolve(contentRoot, "pages");
  const sharedDir = resolve(contentRoot, "shared");
  const collectionsDir = resolve(contentRoot, "collections");

  const sharedCache = new Map();
  const collectionConfigCache = new Map();
  const collectionMetadataCache = new Map();

  async function loadSharedComponent(componentId) {
    const normalized = String(componentId || "").trim();
    if (!normalized) {
      return null;
    }

    if (sharedCache.has(normalized)) {
      return sharedCache.get(normalized);
    }

    const filePath = resolve(sharedDir, `${normalized}.json`);
    try {
      const config = await readJson(filePath);
      sharedCache.set(normalized, config);
      return config;
    } catch {
      sharedCache.set(normalized, null);
      return null;
    }
  }

  async function loadCollectionConfig(collectionId) {
    const normalized = String(collectionId || "").trim();
    if (!normalized) {
      return null;
    }

    if (collectionConfigCache.has(normalized)) {
      return collectionConfigCache.get(normalized);
    }

    try {
      const config = await readJson(
        resolve(collectionsDir, normalized, "_config.json"),
      );
      collectionConfigCache.set(normalized, config);
      return config;
    } catch {
      collectionConfigCache.set(normalized, null);
      return null;
    }
  }

  async function loadCollectionItemsMetadata(collectionId) {
    const normalized = String(collectionId || "").trim();
    if (!normalized) {
      return { collectionId: "", items: [] };
    }

    if (collectionMetadataCache.has(normalized)) {
      return collectionMetadataCache.get(normalized);
    }

    let itemEntries = [];
    try {
      itemEntries = await readdir(resolve(collectionsDir, normalized), {
        withFileTypes: true,
      });
    } catch {
      const emptyResult = { collectionId: normalized, items: [] };
      collectionMetadataCache.set(normalized, emptyResult);
      return emptyResult;
    }

    const jsonItemFiles = itemEntries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
      .filter((entry) => entry.name !== "_config.json")
      .map((entry) => entry.name)
      .sort((a, b) => a.localeCompare(b));

    const items = [];
    for (const fileName of jsonItemFiles) {
      try {
        const item = await readJson(
          resolve(collectionsDir, normalized, fileName),
        );
        const metadata = { ...(item && typeof item === "object" ? item : {}) };
        delete metadata.content;
        const fileBaseName = toBaseName(fileName);
        const itemId = String(item?.id || fileBaseName);
        items.push({
          id: itemId,
          fileBaseName,
          title: item?.title || itemId,
          metadata,
        });
      } catch {
        // Ignore malformed items so one broken file does not stop publishing.
      }
    }

    const result = {
      collectionId: normalized,
      items,
    };
    collectionMetadataCache.set(normalized, result);
    return result;
  }

  const pageFiles = (await readdir(pagesDir, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });

  if (appRoot) {
    for (const name of ["theme.css", "base.css"]) {
      try {
        await copyFile(
          resolve(appRoot, "src/website/styles", name),
          resolve(outputDir, name),
        );
      } catch {
        /* optional */
      }
    }

    try {
      await copyFile(
        resolve(appRoot, "dist-pub/published.js"),
        resolve(outputDir, "published.js"),
      );
    } catch {
      /* optional — published.js is created by npm run build:pub */
    }

    try {
      await copyComponentStyles(appRoot, outputDir);
    } catch {
      /* optional */
    }
  }

  await copyDirectoryRecursive(
    resolve(contentRoot, "images"),
    resolve(outputDir, "images"),
  );

  await copyDirectoryRecursive(resolve(contentRoot, "public"), outputDir);

  const published = [];
  const warnings = [];

  for (const pageFileName of pageFiles) {
    const pagePath = resolve(pagesDir, pageFileName);
    const pageConfig = await readJson(pagePath);
    const fileBaseName = toBaseName(pageFileName);

    const urlPath = normalizePublishedUrlPath(pageConfig?.url, fileBaseName);
    let outputPath;
    let outputFileName;
    if (!urlPath) {
      outputPath = resolve(outputDir, "index.html");
      outputFileName = "index.html";
    } else if (urlPath === "404") {
      outputPath = resolve(outputDir, "404.html");
      outputFileName = "404.html";
    } else {
      const outputDirectory = resolve(outputDir, urlPath);
      await mkdir(outputDirectory, { recursive: true });
      outputPath = resolve(outputDirectory, "index.html");
      outputFileName = `${urlPath}/index.html`;
    }

    const { html, warnings: pageWarnings } = await generatePageHtml({
      pageConfig,
      loadSharedComponent,
      loadCollectionConfig,
      loadCollectionItemsMetadata,
    });

    await writeFile(
      outputPath,
      withGeneratedHtmlHeader(
        useAbsolutePublishAssetPaths(stripViteClientScript(html)),
      ),
      "utf8",
    );

    published.push({
      pageId: pageConfig?.id || fileBaseName,
      fileName: outputFileName,
      outputPath,
    });

    for (const warning of pageWarnings) {
      warnings.push(`[${urlPath || fileBaseName}] ${warning}`);
    }
  }

  const collectionEntries = (
    await readdir(collectionsDir, { withFileTypes: true })
  )
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  for (const collectionId of collectionEntries) {
    const collectionConfig = await loadCollectionConfig(collectionId);
    if (!collectionConfig) {
      continue;
    }

    const collectionTemplateContent =
      Array.isArray(collectionConfig?.content) &&
      collectionConfig.content.length > 0
        ? collectionConfig.content
        : [
            {
              id: "section-collection-template",
              type: "section",
              content: [],
              settings: {},
            },
          ];

    const itemMetadata = await loadCollectionItemsMetadata(collectionId);
    const items = Array.isArray(itemMetadata?.items) ? itemMetadata.items : [];

    for (const itemMeta of items) {
      const itemId = String(itemMeta?.id || "").trim();
      if (!itemId) {
        continue;
      }
      const fileBaseName = String(itemMeta?.fileBaseName || itemId);

      let itemConfig;
      try {
        itemConfig = await readJson(
          resolve(collectionsDir, collectionId, `${fileBaseName}.json`),
        );
      } catch {
        continue;
      }

      const outputUrlPath = normalizePublishedUrlPath(
        itemConfig?.metadata?.url ||
          itemConfig?.metadata?.sourceUrl ||
          itemConfig?.url,
        `/collections/${collectionId}/${itemId}`,
      );
      if (!outputUrlPath) {
        continue;
      }

      const outputDirectory = resolve(outputDir, outputUrlPath);
      const outputPath = resolve(outputDirectory, "index.html");

      const pageTemplate = {
        id: itemId,
        title: itemConfig?.title || itemId,
        content: collectionTemplateContent,
      };

      const tokenValues = buildItemTemplateTokenValues(itemConfig);

      const { html, warnings: pageWarnings } = await generatePageHtml({
        pageConfig: pageTemplate,
        loadSharedComponent,
        loadCollectionConfig,
        loadCollectionItemsMetadata,
        tokenValues,
        collectionItemContent: Array.isArray(itemConfig?.content)
          ? itemConfig.content
          : [],
      });

      await mkdir(outputDirectory, { recursive: true });
      await writeFile(
        outputPath,
        withGeneratedHtmlHeader(
          useAbsolutePublishAssetPaths(stripViteClientScript(html)),
        ),
        "utf8",
      );

      published.push({
        pageId: `${collectionId}/${itemId}`,
        fileName: `${outputUrlPath}/index.html`,
        outputPath,
      });

      for (const warning of pageWarnings) {
        warnings.push(`[${collectionId}/${itemId}] ${warning}`);
      }
    }
  }

  const sitemapResult = await writeSitemap({
    outputDir,
    published,
    siteUrl,
  });
  if (sitemapResult?.fileName) {
    published.push(sitemapResult);
  }

  return {
    ok: true,
    outputDir,
    pages: published,
    warnings,
  };
}

function publishedEntryToUrlPath(fileName) {
  const normalized = String(fileName || "").replace(/^\/+/, "");
  if (!normalized || normalized === "index.html") {
    return "/";
  }
  if (normalized === "404.html") {
    return null;
  }
  if (normalized.endsWith("/index.html")) {
    return `/${normalized.slice(0, -"index.html".length)}`;
  }
  return `/${normalized}`;
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

async function writeSitemap({ outputDir, published, siteUrl }) {
  const trimmedSiteUrl = String(siteUrl || "")
    .trim()
    .replace(/\/+$/, "");
  const seen = new Set();
  const entries = [];

  for (const entry of published) {
    const urlPath = publishedEntryToUrlPath(entry?.fileName);
    if (!urlPath || seen.has(urlPath)) {
      continue;
    }
    seen.add(urlPath);
    const loc = trimmedSiteUrl ? `${trimmedSiteUrl}${urlPath}` : urlPath;
    entries.push(`  <url><loc>${escapeXml(loc)}</loc></url>`);
  }

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join("\n")}
</urlset>
`;

  const outputPath = resolve(outputDir, "sitemap.xml");
  await writeFile(outputPath, xml, "utf8");

  return {
    pageId: "sitemap",
    fileName: "sitemap.xml",
    outputPath,
  };
}
