import { editorRenderSection } from "./site-section/site-section";
import { editorRenderContainer } from "./container/container.editor";
import { editorRenderForm } from "./form/form.editor";
import { editorRenderInput } from "./input/input.editor";
import { editorRenderCaptcha } from "./captcha/captcha.editor";
import { editorRenderCheckbox } from "./checkbox/checkbox.editor";
import { editorRenderShared } from "./shared/shared.editor";
import { editorRenderText } from "./text/text.editor";
import { editorRenderImage } from "./image/image.editor";
import { editorRenderButton } from "./button/button.editor";
import { editorRenderEmbed } from "./embed/embed.editor";
import { editorRenderSocialMedia } from "./social-media/social-media.editor";
import { editorRenderGallery } from "./gallery/gallery.editor";
import { editorRenderSlider } from "./slider/slider.editor";
import { editorRenderNavbar } from "./navbar/navbar.editor";
import { editorRenderCollection } from "./collection/collection.editor";
import { editorRenderCollectionContent } from "./collection-content/collection-content.editor";

const renderComponents = new Map();
renderComponents.set("section", editorRenderSection);
renderComponents.set("container", editorRenderContainer);
renderComponents.set("form", editorRenderForm);
renderComponents.set("input", editorRenderInput);
renderComponents.set("captcha", editorRenderCaptcha);
renderComponents.set("checkbox", editorRenderCheckbox);
renderComponents.set("shared", editorRenderShared);
renderComponents.set("text", editorRenderText);
renderComponents.set("image", editorRenderImage);
renderComponents.set("button", editorRenderButton);
renderComponents.set("embed", editorRenderEmbed);
renderComponents.set("social-media", editorRenderSocialMedia);
renderComponents.set("gallery", editorRenderGallery);
renderComponents.set("slider", editorRenderSlider);
renderComponents.set("navbar", editorRenderNavbar);
renderComponents.set("collection", editorRenderCollection);
renderComponents.set("collection-content", editorRenderCollectionContent);

export { renderComponents };
