import { editorRenderSiteSection } from "./site-section/site-section";
import { editorRenderContainer } from "./container/container";
import { editorRenderForm } from "./form/form";
import { editorRenderInput } from "./input/input";
import { editorRenderShared } from "./shared/shared";
import { editorRenderText } from "./text/text";
import { editorRenderImage } from "./image/image";
import { editorRenderButton } from "./button/button";
import { editorRenderEmbed } from "./embed/embed";
import { editorRenderSocialMedia } from "./social-media/social-media";
import { editorRenderGallery } from "./gallery/gallery";
import { editorRenderSlider } from "./slider/slider";
import { editorRenderCollection } from "./collection/collection";
import { editorRenderCollectionContent } from "./collection-content/collection-content";

const renderComponents = new Map();
renderComponents.set("section", editorRenderSiteSection);
renderComponents.set("container", editorRenderContainer);
renderComponents.set("form", editorRenderForm);
renderComponents.set("input", editorRenderInput);
renderComponents.set("shared", editorRenderShared);
renderComponents.set("text", editorRenderText);
renderComponents.set("image", editorRenderImage);
renderComponents.set("button", editorRenderButton);
renderComponents.set("embed", editorRenderEmbed);
renderComponents.set("social-media", editorRenderSocialMedia);
renderComponents.set("gallery", editorRenderGallery);
renderComponents.set("slider", editorRenderSlider);
renderComponents.set("collection", editorRenderCollection);
renderComponents.set("collection-content", editorRenderCollectionContent);

export { renderComponents };
